describe('Login Admin', () => {
  it('passes', () => {
    cy.visit('http://127.0.0.1:8000/homepage/login')
    cy.get('body')
    cy.get('#email').type("admin@gmail.com")
    cy.get('#password').type("password")
    cy.get('.btn-primary').click()
    cy.get('.main-sidebar')
    cy.get('.nav-pills > :nth-child(2) > [href="#"]').click()
    // CRUD Merk
    cy.get('.menu-is-opening > .nav > :nth-child(1) > .nav-link').click()
    cy.get('.float-right > .btn').click()
    cy.get('#code').type("19")
    cy.get('#name').type("Jagwar")
    cy.get('.btn').click()
    cy.get(':nth-child(7) > :nth-child(3) > form > .btn-primary').click()
    cy.get('#code').type("20")
    cy.get('#name').type("Jagwarr")
    cy.get('.btn').click()
    cy.get(':nth-child(7) > :nth-child(3) > form > .btn-danger').click()
    //CRUD Mobil
    cy.get('.fa-car').click()
    cy.get('.menu-is-opening > .nav > :nth-child(2) > .nav-link').click()
    cy.get('.float-right > .btn').click()
    cy.get('#code').type("40000")
    cy.get('#name').type("Toyota Venders")
    cy.get('#desc').type("Toyota paling toyota")
    cy.get('#amount').type("2")
    cy.get('#price').type(40000)
    cy.get('#status').type("Active")
    cy.get('.btn').click()
    cy.get('.ml-3').click()
    cy.get('.ml-3').click()
    cy.get('.ml-3').click()
    cy.get('.ml-3').click()
    cy.get('.btn-danger').click()
    cy.get(':nth-child(6) > .nav-link').click()
  })
})